### ISSUE TITLE
How to properly retry workers if zeebe goes down?

### ISSUE THREAD

**Issue by sungodavi** [zeebe-io/zeebe-client-node-js#164]
I am running zeebe in my local docker container, and I am trying to figure out how to reset the worker long poll if zeebe were to restart. onConnnectionError doesn't get triggered when zeebe goes down, so I don't know what to listen to.

**Comment by jwulf** [comment]
Version 0.23.3 of the client uses 1.0.4 of @grpc/grpc-js, to pull in https://github.com/grpc/grpc-node/issues/144

**Comment by eetay** [comment]
@jwulf  when is 0.23.3 expected to be released?

**Comment by jwulf** [comment]
It's been out for a while now, and this issue should be resolved. I'm going to close this issue, and if it re-presents, please reopen it.
