### ISSUE TITLE
Periodical INFO Error messages

### ISSUE THREAD

**Issue by jetdream** [zeebe-io/zeebe-client-node-js#176]
From time to time I see messages like this in console NodeJs client application with Job handlers:

    21:28:34.923 | zeebe |  [Task1 (batch)] INFO: Stalled on Grpc Error
    21:28:34.927 | zeebe |  [Task1 (batch)] INFO: Grpc Stream Error: 2 UNKNOWN: 
    21:45:56.763 | zeebe |  [Task2 (batch)] INFO: Stalled on Grpc Error
    21:45:56.767 | zeebe |  [Task2 (batch)] INFO: Grpc Stream Error: 2 UNKNOWN: 
    21:50:57.481 | zeebe |  [SendMessage (batch)] INFO: Stalled on Grpc Error
    21:50:57.483 | zeebe |  [SendMessage (batch)] INFO: Grpc Stream Error: 2 UNKNOWN: 
 
I'm confused seeing error messages with INFO verbose level.
There is no real issues though, everything works fine.

What is the reason for these messages? 
Should I do something to fix this?

I use NodeJS client 0.23.2
Zeebe 0.24.1

**Comment by jwulf** [comment]
INFO level includes ERROR, so at the INFO level you will see ERROR messages.

You can probably safely ignore this message. Which means that it shouldn't be emitted.

This particular error message is generated by the GRPC client in response to something that I haven't been able to track down in the underlying protocol connection.

I could debounce this particular error, and suppress it if it is transient....

**Comment by jetdream** [comment]
Okay, thank you.

**Comment by deliakzy** [comment]
Hi 
Could you please tell me,  how this error was solved, I just configured zeebe in a container and we are making calls to connect and I get this error.
