### ISSUE TITLE
When publishing to circle ci the gh-pages branch fails

### ISSUE THREAD

**Issue by s3than** [zeebe-io/zeebe-client-node-js#60]
When publishing to circle ci the gh-pages branch fails, due to the removal of files there is no circleci config which then fails in Circle CI

**Comment by s3than** [comment]
```Only build pull requests

By default, we will build all the commits for this project. Once turned on, we will only build branches that have associated pull requests open.

Note: For your default branch, we will always build all commits.
```
We might look at implementing this from circle ci

**Comment by jwulf** [comment]
Is this still an issue?

**Comment by s3than** [comment]
Still an issue, low priority but annoying

**Comment by jwulf** [comment]
Is there any way I can fix this? Do I add a CircleCI file to that branch?

**Comment by jwulf** [comment]
@s3than did this fix it?

**Comment by s3than** [comment]
Nope.. when the doc gets generated we need to put a .circleci/config.yaml in that directory

**Comment by kbakk** [comment]
@jwulf The README.md (and About repo section) refers to docs page https://creditsenseau.github.io/zeebe-client-node-js/ ([README.md#L9](https://github.com/zeebe-io/zeebe-client-node-js/blame/aaa9c8ce7839e3c13efb0eaa6961013183d4d1c2/README.md#L9)) however that page is returning a 404 now. All documentation seems to exist in the README.md, so is the doc link needed? It's a bit confusing.

**Comment by s3than** [comment]
@kbakk When we moved the repo to Zeebe from Creditsense it looks like we missed that one. Thanks I'll organise a PR
